name: Daisy
on:
  release:
    types: [published]
  workflow_dispatch: # para ejecutarlo manualmente

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # para usar Trusted Publishing

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      run: pip install uv

    - name: Build package
      run: uv build --no-sources

    - name: Publish to PyPI
      run: uv publish --token 
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
